# AWS ECS/Production Docker Compose
version: '3.8'

services:
  chatbot:
    build: .
    ports:
      - "8501:8501"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - BEDROCK_MODEL_ID=anthropic.claude-3-sonnet-20240229-v1:0
    restart: unless-stopped